config/routes.rb
Rails.application.routes.draw do
  resources :employers do
    member do
      get 'verify_attribute'
      post 'verify_attribute'
    end
  end

  root 'employers#index'

end

app/models/employer.rb
# == Schema Information
#
# Table name: employers
#
#  id                              :integer          not null, primary key
#  name                            :string
#  email                           :string
#  date_of_birth                   :date
#  gender                          :string
#  location                        :string
#  phone_number                    :string
#  email_verified                  :boolean          default(FALSE)
#  phone_number_verified           :boolean          default(FALSE)
#  email_verification_token        :string
#  phone_number_verification_token :string
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#

class Employer < ActiveRecord::Base
  CONFIRMATION_TOKEN_LENGTH = 5
  validates_presence_of :email, :location, :phone_number, :name
  before_update :reset_token
  after_create :reset_email_token, :reset_phone_number_token
  include Rails.application.routes.url_helpers

  def verified?
    email_verified? & phone_number_verified?
  end

  def verify_phone_number(token)
    if phone_number_verified?
      errors.add(:base, 'Already Verified')
      return false
    end
    if phone_number_verification_token == token
      update_attributes(phone_number_verified: true)
    else
      errors.add(:base, 'Wrong validation code')
      false
    end
  end

  def verify_email(token)
    if email_verified?
      errors.add(:base, 'Already Verified')
      return false
    end
    if email_verification_token == token
      update_attributes(email_verified: true)
    else
      errors.add(:base, 'Wrong validation code')
      false
    end
  end

  private

  def reset_token
    reset_phone_number_token if phone_number_changed?
    reset_email_token if email_changed?
  end

  def reset_phone_number_token
    transaction do
      self.phone_number_verification_token = generate_confirmation_token
      self.phone_number_verified = false
    end
    send_phone_number_verification_token
  end

  def reset_email_token
    transaction do
      self.email_verification_token = generate_confirmation_token
      self.email_verified = false
    end
    send_email_verification_token
  end

  def generate_confirmation_token
    array = Array(0..9) + Array('a'..'z') + Array('A'..'Z')
    array.sample(CONFIRMATION_TOKEN_LENGTH).join
  end

  def send_phone_number_verification_token
    twilio_client.messages.create(
      from: ENV['TWILIO_NUMBER'],
      to: phone_number,
      body: "Your verification code  \n#{phone_number_verification_token}, click  #{verify_attribute_employer_url(self,code: phone_number_verification_token,type: :phone_number )}"
    ).delay
  end

  def send_email_verification_token
    EmployerMailer.email_verification(self).deliver_later
  end

  def twilio_client
    @twilio_client ||= Twilio::REST::Client.new ENV['TWILIO_SID'], ENV['TWILIO_TOKEN']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy, :verify_attribute]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /employees/1/verify_attribute
  def verify_attribute
    type = params[:attribute] || 'email'
    code = params[:code]
    if type == 'email'
      @employer.verify_email(code)
    elsif type == 'email'
      @employer.verify_phone_number(code)
        end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employer
    @employer = Employer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employer_params
    params.require(:employer).permit(:name, :email, :gender, :phone_number, :date_of_birth, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@employer) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div>
   <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Gender</th>
      <th>Phone number</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.name %></td>
        <td><%= employer.email %></td>
        <td><%= employer.gender %></td>
        <td><%= employer.phone_number %></td>
        <td><%= employer.date_of_birth %></td>
        <td><%= link_to 'Show', employer %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
        <td><%= link_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_employer_path %>

app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form' %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employer.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @employer.gender %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @employer.phone_number %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @employer.date_of_birth %>
</p>
<p>
<strong> Email verified </strong>
<%= @employer.email_verified? %>
</p>
<p>
<strong> Phone number verified? </strong>
<%= @employer.phone_number_verified? %>

</p>

<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>

app/views/employers/verify_attribute.html.erb
<% if @employer.errors.present? %>
  <%= @employer.errors.full_messages %>
<% else %>
Verified successfully
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>